{
 "title": "PG обзор (курс)",
 "tags": [ "pg-course" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Активные подключения (pg_stat_database)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends) by (datname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Транзакции в секунду (по базам)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[1m]) + rate(pg_stat_database_xact_rollback[1m])",
     "legendFormat": "коммиты+роллбеки"
    }
   ]
  },
  {
   "title": "Запас подключений к лимиту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_settings_max_connections - sum(pg_stat_database_numbackends) by (datname)",
     "legendFormat": "свободно"
    }
   ]
  }
 ]
}